name: Daily Word Email

on:
  schedule:
    - cron: '30 1 * * *'   # 7:00 AM IST
  workflow_dispatch:

jobs:
  send-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send daily word email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          START_DATE: ${{ secrets.START_DATE }}
        run: |
          python app.py
